### ISSUE TITLE
扩充词表后，如何做增量预训练

### ISSUE THREAD

**Issue by mc112611** [ymcui/Chinese-LLaMA-Alpaca-3#108]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Llama-3-Chinese-8B（基座模型）

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
因为需要做某个垂直领域的llama3，由于包含很多专有词汇，直接做指令微调效果甚微。   所以想请教一下如何做增量预训练。或者其他可以让llama3更适合某一专业领域的训练方法。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by fortune-ai** [comment]
请问一下，llama3的词表是如何扩充的？

**Comment by mc112611** [comment]
> 请问一下，llama3的词表是如何扩充的？

查一下bpe 分词，以及词表vocab编码，以及加载tokenizer时候时候加载vocab相关代码。     应该有很多框架支持预训练阶段了，可以看一下。这一段工作很多时候是自己做。但是不同的模型词表构建方式不同。训练框架集成不知道有没有做。我也在等项目组回复嘿嘿😁
