### ISSUE TITLE
MMLU 评估效果差异，列举的实际评估数值与meta官方效果存在差距

### ISSUE THREAD

**Issue by mikeluck** [ymcui/Chinese-LLaMA-Alpaca-3#12]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Llama-3-Chinese-8B（基座模型）

### 操作系统

macOS

### 详细描述问题

仓库里面提到的 MMLU 评估数据集中的 llama-3-8b 在 valid，test的5-shot的meta官方的pretrain和 instruct 存在差异; 而实际上的官方的原始模型都是要比 Chinese-Llama-3-8B的评估数值要高的

- 仓库里面的MMLU
<img width="1007" alt="image-20240430172020883" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/2116271/d558fe91-00af-48be-823b-c66ce8f3bf8f">

- meta官方llama-3-8b
<img width="1087" alt="image-20240430172052160" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/2116271/dc85bd66-9d69-4bcd-a8a6-63b668412db4">
- meta官方llama-3-8b-in
<img width="996" alt="image-20240430172107434" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/2116271/85cbecaa-c1fa-42e7-ae81-86a356363df0">

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
评测脚本不一致导致的，我们用的本仓库里的代码跑的。
