### ISSUE TITLE
只能用cpu跑吗？我用的gpt4all这个软件，添加模型跑的，但是提示只能用cpu跑，而跑其他模型时候，会选择默认的gpu跑

### ISSUE THREAD

**Issue by zhai-hello** [ymcui/Chinese-LLaMA-Alpaca-3#16]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Windows

### 详细描述问题

![Snipaste_2024-04-30_22-11-02](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/150640855/4fa1ebcd-550f-4ede-a30c-bbfa2b47a402)
其他模型就可以用gpu跑，不知道为什么？
![GPU跑](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/150640855/cbff163a-0241-4479-aea9-1156810461a1)

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
原版模型能用GPU，我们的模型也能。

**Comment by zhai-hello** [comment]
哦，抱歉，可能是我显卡显存不足（12G显存)，然后自动选择cpu了（电脑内存32G）
