### ISSUE TITLE
预训练base时的学习率多少

### ISSUE THREAD

**Issue by OKC13** [ymcui/Chinese-LLaMA-Alpaca-3#18]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Llama-3-Chinese-8B（基座模型）

### 操作系统

None

### 详细描述问题

预训练base时的学习率多少？我在想参考下，设置sft学习率。谢谢

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
我们SFT阶段使用的学习率是1e-4，bs=1K，你可以根据实际情况调整（观察开发集loss等手段）。

**Comment by OKC13** [comment]
请问预训练的lr多大呢



---原始邮件---
发件人: "Yiming ***@***.***&gt;
发送时间: 2024年5月2日(周四) 上午9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ymcui/Chinese-LLaMA-Alpaca-3] 预训练base时的学习率多少 (Issue #18)




 
我们SFT阶段使用的学习率是1e-4，bs=1K，你可以根据实际情况调整（观察开发集loss等手段）。
