### ISSUE TITLE
坐等/script/openai_server_demo/的创建

### ISSUE THREAD

**Issue by xiaoToby** [ymcui/Chinese-LLaMA-Alpaca-3#2]
加油！期待好消息！

**Comment by ymcui** [comment]
教程：https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/openai_api_zh

**Comment by xiaoToby** [comment]
> 教程：https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/openai_api_zh

Good job! ❤️❤️

**Comment by xiaoToby** [comment]
> 教程：https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/openai_api_zh

How about 70B?
There is a problem that it needs at least 8 pieces of gpus when doing inference job
