### ISSUE TITLE
编码效率问题。

### ISSUE THREAD

**Issue by xiaoshengjun** [ymcui/Chinese-LLaMA-Alpaca-3#23]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Llama-3-Chinese-8B（基座模型）

### 操作系统

Linux

### 详细描述问题

https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/faq_zh，问题一中指出，llama3的编码效率测试，请问这个编码效率是什么？以及是否可以告知是怎么测试的？感谢！

**Comment by ymcui** [comment]
参阅我们在Mixtral上的论文 Section5.1：https://arxiv.org/abs/2403.01851
