### ISSUE TITLE
通过ollama加载ggml-model-q8_0.gguf后来提问，发现问题后面的回答都是无用信息，而且一直不结束

### ISSUE THREAD

**Issue by JiesenSun** [ymcui/Chinese-LLaMA-Alpaca-3#25]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Linux

### ollama版本

0.1.32

### 模型文件

modelscope社区，llama-3-chinese-8b-instruct-gguf/ggml-model-q8_0.gguf

### 详细描述问题

模型推理回答后面很多无用信息，而且不能结束。
modelfile如下，参考了github下的样例。
```
FROM /opt/llm/llama-3-chinese-8b-instruct-gguf/ggml-model-q8_0.gguf
TEMPLATE """{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>"""
SYSTEM """"""
PARAMETER num_keep 24
PARAMETER stop <|start_header_id|>
PARAMETER stop <|end_header_id|>
PARAMETER stop <|eot_id|>
PARAMETER stop assistant
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
>>> 天空为什么是蓝色的？
天空的颜色主要由大气中的氮氧化合物和分子吸收、散射太阳光而产生。当太阳光通过地球的大气层时，其中部分波长被这些大气成分所吸收，特别是在短波段中。蓝色的波长比其他颜色更容易受到这种效应的影响，因此在进入眼睛之前，被传播和反射到我们头顶上方的天空中的光线呈现出更多的蓝色。

然而，这个过程不是完全均匀的大气散射，具体而言大约有70%的太阳光被地球表面的物体吸收，只有剩下的30%穿过了大气层并到达我们的眼睛。而其中一部分在通过地平线时，被反弹回来的天空颜色呈现出橙、红或粉红。这些不同的散射效果综合起来，最终形成我们看到的蓝色的天空。

值得注意的是，大气中的水蒸汽和尘埃颗粒也会对太阳光产生吸收和散射效应，进一步影响了天空颜色。不过总体而言，我们眼中所见到的蓝色主要是由大气分子在短波长范围内的散射造成的。

此外，大气压力、温度以及地球自转等因素也会对太阳光的传播路径产生一定影响，但对于天空呈现出的总体颜色的决定并不重要。因此，蓝色是我们常见到的大多数情况下看到的天空颜色，这种散射效应使得蓝波长比其他颜色更容易被吸收和反弹到我们的眼睛上，使其看起来更加明亮而丰富。

综上所述，天空呈现出蓝色的主要原因是大气中氮氧化合物等成分在短波段的散射效应，而这个过程导致了太阳光线穿过大气层时更多地反弹到我们的眼睛，因此我们感知到的颜色为蓝色。当然，不同的大气条件和时间会对天空呈现出的具体颜色产生微小但不同的影响，但总体而言，蓝色是常见的天空颜色之一。
```sql
SELECT DISTINCT 
  customer_id,
  order_status, 
  COUNT(*) AS order_count
FROM orders 
GROUP BY customer_id, order_status;
```

这个查询语句首先从`orders`表中选择出唯一的`customer_id`、订单状态（`order_status`）和一个计算出的数量计数列（`COUNT(*)`）。然后，它使用 `DISTINCT` 关键字来确保在结果集中每个订单状态只出现一次。最后，通过将查询分组根据`customer_id`和`order_status`进行统计，以获取每个客户的订单数量，并为其提供一个总结计数列（`AS order_count`）。

这个查询可以用于检索出不同客户的订购情况，其中包含他们在各个不同的状态下的订单信息。例如，给定某个特定的时间段内所有客户的订单统计，可以使用这样的语句来获取每位顾客在提交、处理和完成等不同阶段中的数量计数。

注意，由于这个查询只返回了不重复且唯一的`order_status`值，因此如果有两个不同的订单状态，例如"提交"（Submitted）和"已完成"（Completed），则结果集中将仅包含一个记录。
```sql
SELECT 
  product_name,
  product_category, 
  AVG(price) AS average_price
FROM products 
GROUP BY product_name, product_category;
```

这个查询语句从`products`表中选择出产品名称、品类和平均价格（通过 `AVG()` 函数计算）三个字段。然后，使用 `GROUP BY` 子句将结果分组根据 `product_name` 和 `product_category`。

该查询可以用于获取不同品种的商品在特定时间段内的销售情况，其中包括每个产品名称和分类，以及平均售价。这对于了解某个企业或商店所出售的各种产品之间的价格差异，或者进行市场调研等方面非常有用。通过使用这个查询，可以比较同一类别下的不同商品的平均价格，并分析哪些商品在该时间段内更受欢迎、更具竞争力。

请注意，这个查询只是一个示例，您可以根据具体需求和实际数据表结构进行调整，以获取所需结果集。
```sql
SELECT 
  COUNT(DISTINCT customer_id) AS unique_customers, 
  SUM(order_amount) AS total_sales, 
(order^C

```

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/ollama_zh#step-1-下载对应平台的应用程序

ollama必须使用0.1.33以上版本。目前最新是0.1.34。

**Comment by JiesenSun** [comment]
> [https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/ollama_zh#step-1-下载对应平台的应用程序](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/ollama_zh#step-1-%E4%B8%8B%E8%BD%BD%E5%AF%B9%E5%BA%94%E5%B9%B3%E5%8F%B0%E7%9A%84%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F)
> 
> ollama必须使用0.1.33以上版本。目前最新是0.1.34。

嗯，升级到0.1.34后，解决了不能结束的问题了，但回答的质量还是存在一些幻觉

**Comment by jcleng** [comment]
猜测可能是和.gguf格式生成或者转换有关, 转换成.gguf格式的时候不太正常的话就会出现幻答, 我测试把qwen2:7b的safetensors转为gguf, 手动转的幻答很严重, 无论设置哪个精度和量化都一样, 官方的gguf格式就没有这个问题
