### ISSUE TITLE
如何将自己的中文词表模型与llama3的tokenizer进行合并

### ISSUE THREAD

**Issue by LXYTSOS** [ymcui/Chinese-LLaMA-Alpaca-3#30]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Others

### 操作系统

Linux

### 详细描述问题

```
python merge_tokenizers.py \
  --llama_tokenizer_dir llama_tokenizer_dir \
  --chinese_sp_model_file chinese_sp_model_file
```

### 依赖情况（代码类问题务必提供）

```
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-70B-Instruct")
```

### 运行日志或截图

使用Chinese-LLaMA-Alpaca中提供的合并脚本似乎不行
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "merge_tokenizers.py", line 22, in <module>
    llama_spm.ParseFromString(llama_tokenizer.sp_model.serialized_model_proto())
AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'sp_model'

```

**Comment by ymcui** [comment]
Llama-3不是sentencepiece词表，你用我们1代2代的词表合并脚本显然不可能起作用。

**Comment by LXYTSOS** [comment]
我自己词表是用sentencepiece训练的，模型类型选的是BPE，这种有什么方法能和llama3的合并么？或者如果要和llama3的词表合并，自己的词表要通过什么方式训练得到？

**Comment by Clown4730** [comment]
Llama3的词表是Tiktoken。你找一下怎扩充Tiktoken词表就能找到方法了

**Comment by LXYTSOS** [comment]
好的，感谢。
