### ISSUE TITLE
 训练出的多个lora如何合并成一个呢

### ISSUE THREAD

**Issue by dusens** [ymcui/Chinese-LLaMA-Alpaca-3#31]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

我训练多个样本集如何合并成一个呢请问

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
1. 当前脚本不支持同时多lora合并，你可以串联合并，先合并lora1，再合并lora2，以此类推
2. 一代项目支持多lora合并，但是没有适配llama3，有需要你可以自行参考修改：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora_low_mem.py
3. 换个思路，不是训练多个lora，而是把训练集合并，训出1个lora

**Comment by dusens** [comment]
好的谢谢我现在就是在用第三种方式
