### ISSUE TITLE
使用Openai_api_server.py,进行推理出现RuntimeError

### ISSUE THREAD

**Issue by xiaoToby** [ymcui/Chinese-LLaMA-Alpaca-3#35]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/40045458/0bfc445a-ad23-423d-8860-587ad1f04b23)
为什么会出现这个问题和该如何解决这个问题

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by xiaoToby** [comment]
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0 

@ymcui @iMountTai

**Comment by ymcui** [comment]
不太清楚。colab上都能跑通，不知道你这个是因为版本问题还是什么总出错。
你参考我跑的colab记录，自行debug吧。

https://colab.research.google.com/drive/1mbHo-kAL_zP-JX8TIdLcYYidpTryw6KP?usp=sharing

**Comment by CodeDevMasterPro** [comment]
@ymcui 你好，我也遇到此类问题，请问你解决了吗？什么情况呢？又是如何解决呢？

**Comment by CodeDevMasterPro** [comment]
@xiaoToby 你好，我也遇到此类问题，请问你解决了吗？什么情况呢？又是如何解决呢？

**Comment by xiaoToby** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/40045458/c1a6ccfc-7d78-4c20-bbff-80df1966262b)
怎么修改这个端口，因为我是用的容器的方式，开启的是其他的端口号

**Comment by xiaoToby** [comment]
> ![image](https://private-user-images.githubusercontent.com/40045458/333399922-c1a6ccfc-7d78-4c20-bbff-80df1966262b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTczOTcsIm5iZiI6MTcxNjUxNzA5NywicGF0aCI6Ii80MDA0NTQ1OC8zMzMzOTk5MjItYzFhNmNjZmMtN2Q3OC00YzIwLWJiZmYtODBkZjE5NjYyNjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAyMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYTYwOTY5OTg1Y2UwZGQ3MzQ5OWFhNGY5ZTk0MmJiN2EzNDRkNjJhZWQxZjMyNDY5MDY4OTE0YzMzMDExMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kMsEICy1wF16KR5a9vveBoFZ4sd-yW1E1TWcX2oUET8) 怎么修改这个端口，因为我是用的容器的方式，开启的是其他的端口号

修改了packeage.json，就行了

**Comment by xiaoToby** [comment]
如果我想要用本地部署的模型，并提供了服务接口，怎么样让插件去使用这个模型？
