### ISSUE TITLE
checkpoint file error

### ISSUE THREAD

**Issue by jeffersyuan1976** [ymcui/Chinese-LLaMA-Alpaca-3#54]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Others

### 操作系统

Windows

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
对于Qwen1.5-0.5B-Chat模型，模型中：
1. 没有pytorch_model.bin
2. 也没有model.safetensors.index.json
3. 也没有pytorch_model.index.json

此时就会报错：
Cannot find base model checkpoints in ${base_model_path}. Please make sure the checkpoints are saved in the HF format.

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
你问错地方了，不是本项目的模型。
