### ISSUE TITLE
请问中文对战平台是如何实现的，会开源相关代码吗

### ISSUE THREAD

**Issue by Infinity4B** [ymcui/Chinese-LLaMA-Alpaca-3#56]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
README中有写，是仿照FastChat（https://chat.lmsys.org/?arena）制作的，基于Gradio。
暂时没有时间整理并开源代码，你可以访问他们的网站或者GitHub了解demo页面的实现。
