### ISSUE TITLE
模型微调时构建数据代码Output缺少终止符（输出重复）

### ISSUE THREAD

**Issue by fangzheng123** [ymcui/Chinese-LLaMA-Alpaca-3#59]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
~/scripts/training/build_dataset.py第32行中，output应该是output = assistant_format.format(content=output)。
不加终止符微调会使得模型生成结果重复，而且不停止。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
感谢提醒，开源仓库里的代码已修复。
模型训练时使用的代码没有这个问题，当时忘记同步了。

**Comment by WEXIJUE** [comment]
我修改了之后为什么还是会生成结果重复，而且不停止？数据集都重新构建了
