### ISSUE TITLE
希望能提高实体和事件提取的能力

### ISSUE THREAD

**Issue by czhcc** [ymcui/Chinese-LLaMA-Alpaca-3#6]
例如姓名，地址，关系等
事件的时间，地点，概要，相关人物等
在指定以JSON格式返回时，能严格按指定的JSON格式返回

**Comment by ymcui** [comment]
未对特定任务进行优化。如有需要，你可以自行尝试和进一步精调。

**Comment by xxllp** [comment]
都要自己微调的吧

**Comment by 20184490** [comment]
您好！
看了您一系列汉化llama的博客教程，深受启发，有些问题想向您请教：
1. 在做llama3的继续预训练的时候，数据集用哪些比较好，是否有开源的数据集推荐？
2. 继续预训练的数据集txt文件是否需要数据的预处理，比如做一些文件 内部文本的隔断，换行等，是否需要把同一类别，相似语义的内容放的近一些？

感谢您
