### ISSUE TITLE
llama3-chinese出了吗

### ISSUE THREAD

**Issue by Belonger** [ymcui/Chinese-LLaMA-Alpaca-3#7]
很期待您家的llama3-chinese，从llama1和llama2看过来，就您这家最正宗！

**Comment by ymcui** [comment]
感谢关注，预计很快将与大家分享模型。

**Comment by Belonger** [comment]
@ymcui 这次train llama3之前有扩充词表吗，我看llama3自身的词表已经有128k了。对于中文而言，扩充再增量预训练词表会不会损坏官方的15T充分预训练时学到的通用能力？

**Comment by hy-2013** [comment]
120b的continual pretraining数据会放出来吗？

**Comment by Godlikemandyy** [comment]
> 感谢关注，预计很快将与大家分享模型。

大佬，第三代的alpaca多轮对话效果怎么样

**Comment by snowday365** [comment]
会有70B么
