### ISSUE TITLE
Merging Instruct-v1 and Instruct-v2

### ISSUE THREAD

**Issue by HuuHuy227** [ymcui/Chinese-LLaMA-Alpaca-3#74]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] I have read the [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki) and [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), we recommend checking the corresponding project for solutions

### Type of Issue

Model conversion and merging

### Base Model

Llama-3-Chinese-8B-Instruct (Chat Model)

### Operating System

Linux

### Describe your issue in detail

In the Training Method of Instruct-v3 "Model merging using inst-v1, inst-v2, and inst-meta, followed by fine-tuning with a small amount of instruction data". Is there any script that describe how to merge inst-v1, inst-v2 ?

### Dependencies (must be provided for code-related issues)

```
# Please copy-and-paste your dependencies here.
```

### Execution logs or screenshots

```
# Please copy-and-paste your logs here.
```

**Comment by leonunix** [comment]
The same interesting here.

**Comment by ymcui** [comment]
Thanks for asking. We use a naive linear merging method, which can be seen as `weighted sum` of these individual models. 
As far as I know, you can easily achieve this by using the tools such as mergekit or similar, as our models share identical neural achitecture.
