### ISSUE TITLE
sft执行慢的情况，请大佬帮忙看看

### ISSUE THREAD

**Issue by lingaoan2024** [ymcui/Chinese-LLaMA-Alpaca-3#75]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Windows

### 详细描述问题

虽然选择的是windows系统，但实际是通过wsl安装的ubuntu搭建的环境
训练模型：llama-3-chinese-8b-instruct-v3
数据如下图
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/172566511/08fe0c89-29e1-4710-b639-c125c7f78e60)
2小时过去了，进度才1%
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/172566511/918e6514-e473-49be-8e2a-a35c2e759cc4)
资源情况如下图
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/assets/172566511/2500dfaa-e64a-4c3b-a785-816923424d1b)
我想知道如何提升效率，只有self_cognition.json数据文件的时候，大概10分钟就训练结束了，但是我发现模型丧失了写作的能力，就是让它写论文，不会写了，只能提供思路和方法。有人告诉我是因为我数据太少，出现过拟合现象。所以我想试试多弄点数据

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by leonunix** [comment]
SFT在我8块GPU的节点上也发现同样的问题，同时显存的占用呈现上下浮动，GPU使用率一直在60%左右，之前的llama2没有这种情况。在llama3的sft才有这个问题。pt上没有发现。同样问一下，开发小组是否也有一样的问题。
