### ISSUE TITLE
提问不同问题显存会增加,相同问题则不会

### ISSUE THREAD

**Issue by Chenhuaqi6** [ymcui/Chinese-LLaMA-Alpaca-3#83]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Linux

### 详细描述问题

提了几个问题后发现显存增加了2-300M,请问下是什么原因呢, 图片是起了3个服务, 箭头指示的是问了3个问题后的显存,与其他2个比增加了1-200M

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
![Uploading WX20240704-165810.png…]()

**Comment by zjj2008se** [comment]
token越长占用显存越大，也就是你如果提交了历史消息，那么token一定会变长的
