### ISSUE TITLE
想詢問一下這次的訓練程式沒有使用deepspeed的原因

### ISSUE THREAD

**Issue by ian08005454** [ymcui/Chinese-LLaMA-Alpaca-3#84]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
救我的理解在多卡訓練的時候deepspeed可以用時間換取空間在叫小顯存的情況下訓練大模型，且在多卡的情況下也能節省顯存。我看在之前的項目都是有使用的，因此想知道這次沒有使用的原因是什麼或是該技術有甚麼不適合的地方嗎?

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
我们实际训练的时候是使用了DeepSpeed的。仓库中的代码只是提供了训练示例。
