### ISSUE TITLE
中文数据集上的模型性能

### ISSUE THREAD

**Issue by jerrywyn** [ymcui/Chinese-LLaMA-Alpaca-3#87]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Llama-3-Chinese-8B（基座模型）

### 操作系统

None

### 详细描述问题

我观察到实验结果部分在中文数据集上llama-3-chinese-8B的性能和原版meta的llama3性能非常接近，性能较高的主要是instruct v3版本。这是否反映了使用llama-3-chinese-8B和使用meta的llama3来做中文数据集上的微调，两者的性能并不会相差很多？主要影响性能的因素是这里instruct微调的方法，而不是这里的基座模型？

**Comment by ymcui** [comment]
预训练数据主要用于补充原版llama3未包含的中文知识，这不一定会直接体现在当前这些下游任务上。
