### ISSUE TITLE
基于我自己的长文本训练数据，如何训练一个中文长文本模型，最长可以支持多长的长度

### ISSUE THREAD

**Issue by jy-101361-1810897** [ymcui/Chinese-LLaMA-Alpaca-3#93]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
取决于你有多少卡，数据有多长（虽然也可多个样本拼接在一起变得更长）。

**Comment by jy-101361-1810897** [comment]
是否基于默认的bash run_sft.sh文件运行，不需要进行代码上的修改吗，以及最大长度的超参数在哪里设置？
